# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kong/httpbin
  pullPolicy: Always

service:
  type: ClusterIP
  internalPort: 80
  externalPort: 80
