# Default values for httpbin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

domains: []

customer: ''
application: ''
environment: ''

eso:
  secretStoreKind: ClusterSecretStore
  secretStoreName: aws-parameter-store
image:
  repository: kong/httpbin
  version: 0.1.0
  pullPolicy: Always

service:
  type: ClusterIP
  internalPort: 80
  externalPort: 80
