# Default values for httpbin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

domains: []

customer: ''

image:
  repository: kong/httpbin
  version: latest
  pullPolicy: Always

service:
  type: ClusterIP
  internalPort: 80
  externalPort: 80
