apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regcred
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  labels:
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.eso.global.secretStoreKind }}
    kind: {{ .Values.eso.global.secretStoreKind }}
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      stringData:
        .dockerconfigjson: "{{ `{{ .mysecret | toString }}` }}"
    creationPolicy: Owner
  data:
  - secretKey: regcred
    remoteRef:
      key: /k8s/{{ .Values.environment }}/global/regcred
