---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}"
  lables:
    {{- include "httpbin.labels" . | nindent 4 }}
spec:
  rules:
    {{- range .Values.domains }}
    - host: {{ . }}
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
              name: {{ include "httpbin.fullname" . }}
              port:
                number: {{ $.Values.service.externalPort }}
    {{- end }}
